import{i as c,a as g,S as h}from"./assets/vendor-951421c8.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p="https://pixabay.com/api/",y="41929630-0ce2e4f7023522073d7143cb8",o={form:document.getElementById("form"),resultContainer:document.getElementById("result-container"),loader:document.querySelector(".loader"),loadMoreBtn:document.getElementById("load-more")},i={query:"",page:1,pageSize:40,maxPage:0};o.form.addEventListener("submit",L);async function L(n){n.preventDefault(),o.resultContainer.innerHTML="",i.page=1,o.loader.classList.remove("is-hidden");const a=n.currentTarget;if(i.query=a.elements.picture.value.trim(),!i.query)return;try{const{hits:t,totalHits:e}=await d(i);t.length===0&&c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),i.maxPage=Math.ceil(e/i.pageSize),m(t),t.length>0&&t.length!==e&&(o.loadMoreBtn.classList.remove("is-hidden"),o.loadMoreBtn.addEventListener("click",s))}catch{c.error({position:"topRight",message:"Something wrong!"})}finally{a.reset(),o.loader.classList.add("is-hidden")}async function s(){i.page+=1,o.loadMoreBtn.disabled=!0,o.loader.classList.remove("is-hidden");try{const{hits:t}=await d(i);m(t),b()}catch{c.error({position:"topRight",message:"Something wrong!"})}finally{o.loadMoreBtn.disabled=!1,o.loader.classList.add("is-hidden")}i.page===i.maxPage&&(o.loadMoreBtn.classList.add("is-hidden"),o.loadMoreBtn.removeEventListener("click",s),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}}function d({query:n,page:a=1,pageSize:s}){return g.get(`${p}`,{params:{key:y,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:a}}).then(({data:t})=>t)}let B=new h(".gallery a",{captionsData:"alt",captionDelay:250});function m(n){const a=n.map(({webformatURL:s,largeImageURL:t,tags:e,likes:r,views:l,comments:u,downloads:f})=>`<li class="gallery-item">
            <a href="${t}">
  <img class="gallery-image" src="${s}" alt="${e}" width="370" heigth="300"></a>
  <ul class="info-list">
    <li class="info-item">Likes: ${r}</li>
    <li class="info-item">Views: ${l}</li>
    <li class="info-item">Comments: ${u}</li>
    <li class="info-item">Downloads: ${f}</li>
  </ul>
</li>`).join("");o.resultContainer.insertAdjacentHTML("beforeend",a),B.refresh()}function b(){if(i.page>1){const n=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:n.height*2,left:0,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
